### ISSUE TITLE
win10无法正常安装

### ISSUE THREAD

**Issue by rwindwh** [alibaba/lightproxy#191]
![image](https://user-images.githubusercontent.com/22764636/87656081-9a388b80-c78b-11ea-99e7-52b21f7df50e.png)
使用管理员权限安装失败，各种权限都给了，不知道是个啥情况

**Comment by xcodebuild** [comment]
安装并不需要管理员权限，只是启动应用时需要管理员身份，需要给应用 `右键 => 属性 => 兼容性 => 以管理员身份运行`。

如果仍然无法启动，说明安装证书的过程失败了。

可以用管理员身份打开一个 `cmd`，然后在 `cmd` 里执行 `LightProxy` 的执行 `exe`，可以在命令行里看到具体的错误信息。

**Comment by rwindwh** [comment]
上面的操作都做了，结果一样

**Comment by xcodebuild** [comment]
似乎最新版是有点问题，我来看看修复下发自我的iPhone------------------ 原始邮件 ------------------发件人: rwindwh  <notifications@github.com>发送时间: 2020年7月16日 17:42收件人: alibaba/lightproxy <lightproxy@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[alibaba/lightproxy] win10无法正常安装 (#191)


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/alibaba/lightproxy/issues/191",
"url": "https://github.com/alibaba/lightproxy/issues/191",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by xcodebuild** [comment]
@rwindwh 尝试重新下载最新版，应该已经解决了

**Comment by rwindwh** [comment]
非常感谢,可以正常使用了
